### ISSUE TITLE
appstream-util doesn't accept MIT license as metadata license

### ISSUE THREAD

**Issue by scx** [hughsie/appstream-glib#323] opened 2019-09-18 21:43 UTC
`appstream-util` doesn't accept the `MIT` license as a metadata license.

According to the Freedesktop specification, `MIT` is a valid license (and even recommended!).
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-contents
https://spdx.org/licenses/

Unfortunately, `appstream-util`/`org.freedesktop.appstream-glib` doesn't accept it anymore, at least as a metadata license:
```
$ flatpak run org.freedesktop.appstream-glib validate build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml
build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml: FAILED:
• tag-invalid           : <metadata_license> is not valid [MIT]
```

```
$ appstream-util validate build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml
build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml: FAILED:
• tag-invalid           : <metadata_license> is not valid [MIT]
• tag-missing           : <translation> not specified
• tag-missing           : <update_contact> is not present
Validation of files failed
```

However, it is still OK for `validate-relax`:
```
$ flatpak run org.freedesktop.appstream-glib validate-relax build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml
build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml: OK
```
```
$ appstream-util validate-relax build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml
build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml: OK
```

And of course, `appstreamcli` has no problem with that:
```
$ appstreamcli validate build/files/share/appdata/com.notepadqq.Notepadqq.appdata.xml
Validation was successful: pedantic: 1
```

Temporary patch ([0007-Update-list-of-allowed-metadata-licences.patch](https://pastebin.com/raw/21eKT5vH)):
```
diff --git a/libappstream-glib/as-app-validate.c b/libappstream-glib/as-app-validate.c
index ccac4e2..c1103ac 100644
--- a/libappstream-glib/as-app-validate.c
+++ b/libappstream-glib/as-app-validate.c
@@ -1046,6 +1046,12 @@ as_app_validate_license (const gchar *license_text, GError **error)
 static gboolean
 as_app_validate_is_content_license_id (const gchar *license_id)
 {
+	if (g_strcmp0 (license_id, "@FSFAP") == 0)
+		return TRUE;
+	if (g_strcmp0 (license_id, "@MIT") == 0)
+		return TRUE;
+	if (g_strcmp0 (license_id, "@0BSD") == 0)
+		return TRUE;
 	if (g_strcmp0 (license_id, "@CC0-1.0") == 0)
 		return TRUE;
 	if (g_strcmp0 (license_id, "@CC-BY-3.0") == 0)
@@ -1062,7 +1068,11 @@ as_app_validate_is_content_license_id (const gchar *license_id)
 		return TRUE;
 	if (g_strcmp0 (license_id, "@GFDL-1.3") == 0)
 		return TRUE;
-	if (g_strcmp0 (license_id, "@FSFAP") == 0)
+	if (g_strcmp0 (license_id, "@BSL-1.0") == 0)
+		return TRUE;
+	if (g_strcmp0 (license_id, "@FTL") == 0)
+		return TRUE;
+	if (g_strcmp0 (license_id, "@FSFUL") == 0)
 		return TRUE;
 	return FALSE;
 }
```

This basically updates the list with values from the reference implementation.

See also:
https://github.com/hughsie/appstream-glib/blob/d9270c52bffde6ebd4fc3e3b4e0d34f802b920db/libappstream-glib/as-app-validate.c#L1046-L1068
https://github.com/ximion/appstream/blob/08f44a7fda48dc639346414687e79ee2e82963dd/src/as-spdx.c#L469-L507

PR is on the way.

**Comment by scx** [comment] 2019-09-18 21:54
See: https://github.com/flathub/org.freedesktop.appstream-glib/issues/6

**Comment by ximion** [comment] 2019-09-18 22:22
This is a duplicate of https://github.com/hughsie/appstream-glib/issues/320
What I find curious is this statement though:
> MIT is a valid license (and even recommended!).

Can you please point out where this is recommended? The spec/documentation shouldn't actually make a recommendation, and uses FSFAP in its examples, usually.

**Closed by ximion** 2019-09-18 22:22 UTC
Labels: duplicate

**Comment by scx** [comment] 2019-09-18 22:27
> Can you please point out where this is recommended? The spec/documentation shouldn't actually make a recommendation, and uses FSFAP in its examples, usually.

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-contents

> Possible license identifiers include:
> * `FSFAP`
> * `CC0-1.0`
> * `CC-BY-3.0`
> * `CC-BY-SA-3.0`
> * `GFDL-1.3`
> * `MIT`

Since this list is a subset of the valid licenses for metadata, I assume that all these examples are recommended.
https://github.com/ximion/appstream/blob/08f44a7fda48dc639346414687e79ee2e82963dd/src/as-spdx.c#L469-L507
